/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: UROD Engine (https://sketchfab.com/Starven38)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/personal-computer-aa398650fe6e4baa8771c71266d842f4
Title: Personal Computer
*/

import { Stars, useGLTF, useTexture } from '@react-three/drei'

const HackerRoom = (props) => {
  const { nodes, materials } = useGLTF('/models/personal_computer.glb');
  const screenTexture = useTexture('/textures/desk/screen.png');


  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.003}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_PC_0.geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_LightMat_0.geometry}
              material={materials.LightMat}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_Screen_0.geometry}
              material={materials.Screen}
              >
                <meshMatcapMaterial map={screenTexture} />
            </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_Keyboard_0.geometry}
              material={materials.Keyboard}
            />

            <mesh>
              <hemisphereLight intensity={20} groundColor="black" />
              <spotLight
                position={[-20, 50, 10]}
                angle={0.12}
                penumbra={1}
                intensity={1}
                castShadow
                shadow-mapSize={1024}
              />
              <pointLight intensity={10} />
            </mesh>

            <Stars
              radius={5} // Radius of the sphere containing stars
              depth={50} // Star layer depth
              count={2000} // Number of stars
              factor={3} // Size of stars
              saturation={0} // Star color saturation
              fade // Fades stars when close to camera
            />

          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/personal_computer.glb')

export default HackerRoom;